export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

    GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',

    GET_USERS_REQUEST: 'GET_USERS_REQUEST',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',

    CREATE_ACCOUNT_REQUEST: 'CREATE_ACCOUNT_REQUEST',
    CREATE_ACCOUNT_FAILURE: 'CREATE_ACCOUNT_FAILURE',
    CREATE_ACCOUNT_SUCCESS: 'CREATE_ACCOUNT_SUCCESS',

    LOGIN_WITH_GOOGLE_REQUEST: 'LOGIN_WITH_GOOGLE_REQUEST',
    LOGIN_WITH_GOOGLE_SUCCESS: 'LOGIN_WITH_GOOGLE_SUCCESS',
    LOGIN_WITH_GOOGLE_FAILURE: 'LOGIN_WITH_GOOGLE_FAILURE',
}


export const chatConstants = {
    CHAT_ON: 'CHAT_ON',
    CHAT_OFF: 'CHAT_OFF',
}

export const conversationConstants = {
    CONVERSATION_REQUEST: 'CONVERSATION_REQUEST',
    CONVERSATION_SUCCESS: 'CONVERSATION_SUCCESS',
    CONVERSATION_FAILURE: 'CONVERSATION_FAILURE',

    GET_CONVERSATION_REQUEST: 'GET_CONVERSATION_REQUEST',
    GET_CONVERSATION_SUCCESS: 'GET_CONVERSATION_SUCCESS',
    GET_CONVERSATION_FAILURE: 'GET_CONVERSATION_FAILURE',

    SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST',
    SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
    SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',

    GET_USERS_MESSAGE_REQUEST: 'GET_USERS_MESSAGE_REQUEST',
    GET_USERS_MESSAGE_SUCCESS: 'GET_USERS_MESSAGE_SUCCESS',
    GET_USERS_MESSAGE_FAILURE: 'GET_USERS_MESSAGE_FAILURE',
}